pokemon:
	python3 pokedex.py pokemon --inputdata pikachu
ability:
	python3 pokedex.py ability --inputdata 1
move:
	python3 pokedex.py move --inputdata 1
item:
	python3 pokedex.py item --inputdata 1
pokemon-ex:
	python3 pokedex.py pokemon --inputdata pikachu --expanded
pokemon-ex-if:
	python3 pokedex.py pokemon --inputfile input.txt --expanded
pokemon-ex-of:
	python3 pokedex.py pokemon --inputdata pikachu --expanded --output pokemon.txt
pokemon-ex-iof:
	python3 pokedex.py pokemon --inputfile input.txt --expanded --output pokemon.txt
